name: gmplabtools
channels:
  # - anaconda-fusion
  - conda-forge
dependencies:
  - ase=3.19.0
  - cycler=0.10.0
  - dscribe=0.3.4  # 0.3.5 available for linux
  - ipykernel
  - ipython
  - ipywidgets
  - joblib=0.14.1  # available in anaconda channel
  - jupyterlab
  - libgfortran
  - matplotlib=3.2.0  # 3.2.1 available
  - mdanalysis=0.20.1
  - numpy=1.18.1
  - pandas=1.0.1
  - pip
  - pybind11=2.4.3  # 2.5.0 available
  - pytest=5.4.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - scikit-learn=0.22.2.post1
  - scipy=1.4.1
  - seaborn=0.10.0
  - setuptools
  - wheel
