FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND=noninteractive && apt-get update \
    && apt-get install -y --no-install-recommends build-essential gfortran python3-dev python3-pip \
    libblas-dev liblapack-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && ln -s /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/liblapack.so \
    && ln -s /usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/libblas.so \

WORKDIR /root

ADD test_environment.txt .

RUN pip3 install -r test_environment.txt

CMD ["/bin/bash"]