mymodule=[]
pymodules=[]

[transform]
plot = true

[transform.trajectories]
C1 = "./TRAJ/autoDIPC1_2us.xyz"
C5 = "./TRAJ/autoDIPC5_2us.xyz"
N0 = "./TRAJ/autoDIPN0_2us.xyz"

[transform.soap_param]
species = ["N"]
periodic = false
rcut = 8
nmax = 8
lmax = 8

[transform.transformer]
name = "PCA"

[transform.transformer.param]
n_components=7

[cluster]
trj_filename = "allsoap.pca"
distance = "minkowski"
size = 1000
p = 2
generate_grid = true
savegrid = "grid"

[cluster.pamm_input]
d = 7
fspread = 0.1
ngrid = 1000
qs = 1
o = "pamm"
trajectory = "allsoap.pca"
readgrid = "grid"
merger = 0.01
bootstrap = 128

[cluster.dendrogram]

[predict.extrapolate_on_files]
C1 = "C1soap.pca"
C5 = "C5soap.pca"
N0 = "N0soap.pca"

[predict]
pamm_output = "pamm"

[predict.size]
C1 = 40
C5 = 40
N0 = 40
